/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qIskBvIZqFD
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

const  page= ()=> {
    // @ts-ignore
    return (
        <div className="flex flex-col min-h-[100vh]">
            <header className="px-4 lg:px-6 h-14 flex items-center">
                <Link className="flex items-center justify-center" href="#">
                    <VeganIcon className="h-6 w-6" />
                    <span className="sr-only">Fashionista</span>
                </Link>
                <nav className="ml-auto flex gap-4 sm:gap-6">
                    <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                        Latest Trends
                    </Link>
                    <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                        Collections
                    </Link>
                    <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                        Designers
                    </Link>
                    <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                        Contact
                    </Link>
                </nav>
            </header>
            <main className="flex-1">
                <section className="w-full py-6 sm:py-12 md:py-24 lg:py-32 xl:py-48">
                    <div className="container px-4 md:px-6">
                        <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
                            <img
                                alt="Fashion Hero"
                                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
                                height="550"
                                src="/placeholder.svg"
                                width="550"
                            />
                            <div className="flex flex-col justify-center space-y-4">
                                <div className="space-y-2">
                                    <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                                        Discover Your Style
                                    </h1>
                                    <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                                        Explore the latest fashion trends and find your style with our curated collections.
                                    </p>
                                </div>
                                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                                    <Link
                                        className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                                        href="#"
                                    >
                                        Explore Now
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
                    <div className="container px-4 md:px-6">
                        <div className="flex flex-col items-center justify-center space-y-4 text-center">
                            <div className="space-y-2">
                                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                                    Style Survey
                                </div>
                                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">What's Your Style?</h2>
                                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                    Take our quick survey to help us understand your style preferences and fashion interests.
                                </p>
                            </div>
                        </div>
                        <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
                            <img
                                alt="Image"
                                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                                height="310"
                                src="/placeholder.svg"
                                width="550"
                            />
                            <div className="flex flex-col justify-center space-y-4">
                                <form className="space-y-4">
                                    <div className="space-y-2">
                                        <Label htmlFor="style">Preferred Style</Label>
                                        <Select id="style">
                                            <option>Casual</option>
                                            <option>Formal</option>
                                            <option>Sporty</option>
                                            <option>Boho</option>
                                            <option>Chic</option>
                                        </Select>
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="interest">Fashion Interests</Label>
                                        <Select id="interest" multiple>
                                            <option>Designer Collections</option>
                                            <option>Street Style</option>
                                            <option>Sustainable Fashion</option>
                                            <option>Vintage Clothing</option>
                                            <option>Accessories</option>
                                        </Select>
                                    </div>
                                    <Button type="submit">Submit</Button>
                                </form>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    )
}


function VeganIcon(props:any) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M2 2a26.6 26.6 0 0 1 10 20c.9-6.82 1.5-9.5 4-14" />
            <path d="M16 8c4 0 6-2 6-6-4 0-6 2-6 6" />
            <path d="M17.41 3.6a10 10 0 1 0 3 3" />
        </svg>
    )
}
export default page;